In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
from IPython.core.display import display, HTML

file_path = "/content/drive/My Drive/Churn Prediction/dataset/a_IBM Telco Customers Churn Datasets.xlsx"
sheets = pd.ExcelFile(file_path).sheet_names
dataframes = {sheet: pd.read_excel(file_path, sheet_name=sheet) for sheet in sheets}

exclude_sheets = ['Population', 'Telco_Churn']

for sheet, df in dataframes.items():
    if sheet not in exclude_sheets:
        print(f"\n=== {sheet} ===\n")

        # Chuyển DataFrame thành HTML có style
        styled_html = df.head(5).T.to_html(classes='table table-bordered', escape=False)
        display(HTML(f"<h3 style='color: blue;'>First 5 Rows from {sheet}</h3>{styled_html}"))

=== Customer_Info ===

=== Service_Options ===

=== Online_Services ===

=== Payment_Info ===

=== Status_Analysis ===

=== Location_Data ===

In [6]:
import pandas as pd
from tabulate import tabulate
from termcolor import colored

# Đọc dữ liệu từ file Excel trên Google Drive
file_path = "/content/drive/My Drive/Churn Prediction/dataset/a_IBM Telco Customers Churn Datasets.xlsx"
sheets = pd.ExcelFile(file_path).sheet_names
dataframes = {sheet: pd.read_excel(file_path, sheet_name=sheet) for sheet in sheets}

# Danh sách sheet không cần hiển thị
exclude_sheets = ['Population', 'Telco_Churn']

# Hàm hiển thị bảng dữ liệu đẹp hơn
def display_tabulate(df, sheet_name):
    print(colored(f"\n=== {sheet_name} ===\n", "blue", attrs=["bold"]))  # Tiêu đề màu xanh dương
    print(tabulate(df.head(5), headers="keys", tablefmt="fancy_grid", showindex=False))

# Duyệt qua từng sheet và hiển thị nếu không thuộc danh sách loại trừ
for sheet, df in dataframes.items():
    if sheet not in exclude_sheets:
        display_tabulate(df, sheet)

=== Customer_Info ===

╒═══════════════╤══════════╤═══════╤════════════╤══════════════════╤═══════════╤══════════════╤════════════════════════╤═══════════╕
│ customer_id   │ gender   │   age │ under_30   │ senior_citizen   │ partner   │ dependents   │   number_of_dependents │ married   │
╞═══════════════╪══════════╪═══════╪════════════╪══════════════════╪═══════════╪══════════════╪════════════════════════╪═══════════╡
│ 0002-ORFBO    │ Female   │    37 │ No         │ No               │ Yes       │ No           │                      0 │ Yes       │
├───────────────┼──────────┼───────┼────────────┼──────────────────┼───────────┼──────────────┼────────────────────────┼───────────┤
│ 0003-MKNFE    │ Male     │    46 │ No         │ No               │ No        │ No           │                      0 │ No        │
├───────────────┼──────────┼───────┼────────────┼──────────────────┼───────────┼──────────────┼────────────────────────┼───────────┤
│ 0004-TLHLJ    │ Male     │    50 │ No         │ No               │ No        │ No           │                      0 │ No        │
├───────────────┼──────────┼───────┼────────────┼──────────────────┼───────────┼──────────────┼────────────────────────┼───────────┤
│ 0011-IGKFF    │ Male     │    78 │ No         │ Yes              │ Yes       │ No           │                      0 │ Yes       │
├───────────────┼──────────┼───────┼────────────┼──────────────────┼───────────┼──────────────┼────────────────────────┼───────────┤
│ 0013-EXCHZ    │ Female   │    75 │ No         │ Yes              │ Yes       │ No           │                      0 │ Yes       │
╘═══════════════╧══════════╧═══════╧════════════╧══════════════════╧═══════════╧══════════════╧════════════════════════╧═══════════╛

=== Service_Options ===

╒═══════════════╤══════════╤════════════════════╤═════════════════╤══════════════════╤═══════════════════════════╤══════════════════╤═════════╤═════════════════════╤═══════════════════════╕
│ customer_id   │   tenure │ internet_service   │ phone_service   │ multiple_lines   │   avg_monthly_gb_download │ unlimited_data   │ offer   │ referred_a_friend   │   number_of_referrals │
╞═══════════════╪══════════╪════════════════════╪═════════════════╪══════════════════╪═══════════════════════════╪══════════════════╪═════════╪═════════════════════╪═══════════════════════╡
│ 0002-ORFBO    │        9 │ Yes                │ Yes             │ No               │                        16 │ Yes              │ nan     │ Yes                 │                     2 │
├───────────────┼──────────┼────────────────────┼─────────────────┼──────────────────┼───────────────────────────┼──────────────────┼─────────┼─────────────────────┼───────────────────────┤
│ 0003-MKNFE    │        9 │ Yes                │ Yes             │ Yes              │                        10 │ No               │ nan     │ No                  │                     0 │
├───────────────┼──────────┼────────────────────┼─────────────────┼──────────────────┼───────────────────────────┼──────────────────┼─────────┼─────────────────────┼───────────────────────┤
│ 0004-TLHLJ    │        4 │ Yes                │ Yes             │ No               │                        30 │ Yes              │ Offer E │ No                  │                     0 │
├───────────────┼──────────┼────────────────────┼─────────────────┼──────────────────┼───────────────────────────┼──────────────────┼─────────┼─────────────────────┼───────────────────────┤
│ 0011-IGKFF    │       13 │ Yes                │ Yes             │ No               │                         4 │ Yes              │ Offer D │ Yes                 │                     1 │
├───────────────┼──────────┼────────────────────┼─────────────────┼──────────────────┼───────────────────────────┼──────────────────┼─────────┼─────────────────────┼───────────────────────┤
│ 0013-EXCHZ    │        3 │ Yes                │ Yes             │ No               │                        11 │ Yes              │ nan     │ Yes                 │                     3 │
╘═══════════════╧══════════╧════════════════════╧═════════════════╧══════════════════╧═══════════════════════════╧══════════════════╧═════════╧═════════════════════╧═══════════════════════╛

=== Online_Services ===

╒═══════════════╤═════════════════╤════════════════════╤═══════════════════╤═════════════════╤═════════════════════╤════════════════════════╤════════════════╤════════════════════╤═══════════════════╤═════════════════╕
│ customer_id   │ phone_service   │ internet_service   │ online_security   │ online_backup   │ device_protection   │ premium_tech_support   │ streaming_tv   │ streaming_movies   │ streaming_music   │ internet_type   │
╞═══════════════╪═════════════════╪════════════════════╪═══════════════════╪═════════════════╪═════════════════════╪════════════════════════╪════════════════╪════════════════════╪═══════════════════╪═════════════════╡
│ 0002-ORFBO    │ Yes             │ Yes                │ No                │ Yes             │ No                  │ Yes                    │ Yes            │ No                 │ No                │ Cable           │
├───────────────┼─────────────────┼────────────────────┼───────────────────┼─────────────────┼─────────────────────┼────────────────────────┼────────────────┼────────────────────┼───────────────────┼─────────────────┤
│ 0003-MKNFE    │ Yes             │ Yes                │ No                │ No              │ No                  │ No                     │ No             │ Yes                │ Yes               │ Cable           │
├───────────────┼─────────────────┼────────────────────┼───────────────────┼─────────────────┼─────────────────────┼────────────────────────┼────────────────┼────────────────────┼───────────────────┼─────────────────┤
│ 0004-TLHLJ    │ Yes             │ Yes                │ No                │ No              │ Yes                 │ No                     │ No             │ No                 │ No                │ Fiber Optic     │
├───────────────┼─────────────────┼────────────────────┼───────────────────┼─────────────────┼─────────────────────┼────────────────────────┼────────────────┼────────────────────┼───────────────────┼─────────────────┤
│ 0011-IGKFF    │ Yes             │ Yes                │ No                │ Yes             │ Yes                 │ No                     │ Yes            │ Yes                │ No                │ Fiber Optic     │
├───────────────┼─────────────────┼────────────────────┼───────────────────┼─────────────────┼─────────────────────┼────────────────────────┼────────────────┼────────────────────┼───────────────────┼─────────────────┤
│ 0013-EXCHZ    │ Yes             │ Yes                │ No                │ No              │ No                  │ Yes                    │ Yes            │ No                 │ No                │ Fiber Optic     │
╘═══════════════╧═════════════════╧════════════════════╧═══════════════════╧═════════════════╧═════════════════════╧════════════════════════╧════════════════╧════════════════════╧═══════════════════╧═════════════════╛

=== Payment_Info ===

╒═══════════════╤════════════════╤═════════════════════╤══════════════════╤════════════════════╤═════════════════════════════════════╤═════════════════╤═════════════════╤════════════════════════════╤═══════════════════════════════╤═════════════════╕
│ customer_id   │ contract       │ paperless_billing   │ payment_method   │   monthly_ charges │   avg_monthly_long_distance_charges │   total_charges │   total_refunds │   total_extra_data_charges │   total_long_distance_charges │   total_revenue │
╞═══════════════╪════════════════╪═════════════════════╪══════════════════╪════════════════════╪═════════════════════════════════════╪═════════════════╪═════════════════╪════════════════════════════╪═══════════════════════════════╪═════════════════╡
│ 0002-ORFBO    │ One Year       │ Yes                 │ Mailed check     │               65.6 │                               42.39 │          593.3  │            0    │                          0 │                        381.51 │          974.81 │
├───────────────┼────────────────┼─────────────────────┼──────────────────┼────────────────────┼─────────────────────────────────────┼─────────────────┼─────────────────┼────────────────────────────┼───────────────────────────────┼─────────────────┤
│ 0003-MKNFE    │ Month-to-Month │ No                  │ Mailed check     │               59.9 │                               10.69 │          542.4  │           38.33 │                         10 │                         96.21 │          610.28 │
├───────────────┼────────────────┼─────────────────────┼──────────────────┼────────────────────┼─────────────────────────────────────┼─────────────────┼─────────────────┼────────────────────────────┼───────────────────────────────┼─────────────────┤
│ 0004-TLHLJ    │ Month-to-Month │ Yes                 │ Electronic check │               73.9 │                               33.65 │          280.85 │            0    │                          0 │                        134.6  │          415.45 │
├───────────────┼────────────────┼─────────────────────┼──────────────────┼────────────────────┼─────────────────────────────────────┼─────────────────┼─────────────────┼────────────────────────────┼───────────────────────────────┼─────────────────┤
│ 0011-IGKFF    │ Month-to-Month │ Yes                 │ Electronic check │               98   │                               27.82 │         1237.85 │            0    │                          0 │                        361.66 │         1599.51 │
├───────────────┼────────────────┼─────────────────────┼──────────────────┼────────────────────┼─────────────────────────────────────┼─────────────────┼─────────────────┼────────────────────────────┼───────────────────────────────┼─────────────────┤
│ 0013-EXCHZ    │ Month-to-Month │ Yes                 │ Mailed check     │               83.9 │                                7.38 │          267.4  │            0    │                          0 │                         22.14 │          289.54 │
╘═══════════════╧════════════════╧═════════════════════╧══════════════════╧════════════════════╧═════════════════════════════════════╧═════════════════╧═════════════════╧════════════════════════════╧═══════════════════════════════╧═════════════════╛

=== Status_Analysis ===

╒═══════════════╤══════════════════════╤════════╤═══════════════════╤═══════════════╤═══════════════╤═══════════════╤══════════════════╤═══════════════════════════════╕
│ customer_id   │   satisfaction_score │   cltv │ customer_status   │   churn_score │ churn_label   │   churn_value │ churn_category   │ churn_reason                  │
╞═══════════════╪══════════════════════╪════════╪═══════════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═══════════════════════════════╡
│ 0002-ORFBO    │                    3 │   2205 │ Stayed            │            65 │ No            │             0 │ Not Applicable   │ nan                           │
├───────────────┼──────────────────────┼────────┼───────────────────┼───────────────┼───────────────┼───────────────┼──────────────────┼───────────────────────────────┤
│ 0003-MKNFE    │                    5 │   5414 │ Stayed            │            66 │ No            │             0 │ Not Applicable   │ nan                           │
├───────────────┼──────────────────────┼────────┼───────────────────┼───────────────┼───────────────┼───────────────┼──────────────────┼───────────────────────────────┤
│ 0004-TLHLJ    │                    1 │   4479 │ Churned           │            71 │ Yes           │             1 │ Competitor       │ Competitor had better devices │
├───────────────┼──────────────────────┼────────┼───────────────────┼───────────────┼───────────────┼───────────────┼──────────────────┼───────────────────────────────┤
│ 0011-IGKFF    │                    1 │   3714 │ Churned           │            91 │ Yes           │             1 │ Dissatisfaction  │ Product dissatisfaction       │
├───────────────┼──────────────────────┼────────┼───────────────────┼───────────────┼───────────────┼───────────────┼──────────────────┼───────────────────────────────┤
│ 0013-EXCHZ    │                    1 │   3464 │ Churned           │            68 │ Yes           │             1 │ Dissatisfaction  │ Network reliability           │
╘═══════════════╧══════════════════════╧════════╧═══════════════════╧═══════════════╧═══════════════╧═══════════════╧══════════════════╧═══════════════════════════════╛

=== Location_Data ===

╒═══════════════╤═══════════════╤════════════╤══════════════╤════════════╤════════════════════╤════════════╤═════════════╕
│ customer_id   │ country       │ state      │ city         │   zip_code │   total_population │   latitude │   longitude │
╞═══════════════╪═══════════════╪════════════╪══════════════╪════════════╪════════════════════╪════════════╪═════════════╡
│ 0002-ORFBO    │ United States │ California │ Frazier Park │      93225 │               4498 │    34.8277 │    -118.999 │
├───────────────┼───────────────┼────────────┼──────────────┼────────────┼────────────────────┼────────────┼─────────────┤
│ 0003-MKNFE    │ United States │ California │ Glendale     │      91206 │              31297 │    34.1625 │    -118.204 │
├───────────────┼───────────────┼────────────┼──────────────┼────────────┼────────────────────┼────────────┼─────────────┤
│ 0004-TLHLJ    │ United States │ California │ Costa Mesa   │      92627 │              62069 │    33.6457 │    -117.923 │
├───────────────┼───────────────┼────────────┼──────────────┼────────────┼────────────────────┼────────────┼─────────────┤
│ 0011-IGKFF    │ United States │ California │ Martinez     │      94553 │              46677 │    38.0145 │    -122.115 │
├───────────────┼───────────────┼────────────┼──────────────┼────────────┼────────────────────┼────────────┼─────────────┤
│ 0013-EXCHZ    │ United States │ California │ Camarillo    │      93010 │              42853 │    34.2278 │    -119.08  │
╘═══════════════╧═══════════════╧════════════╧══════════════╧════════════╧════════════════════╧════════════╧═════════════╛